---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - На сайте должна быть возможность выбора количества товара
  - Пользователь должен иметь возможность удалить товар из корзины
  - Корзина должна храниться в сессии браузера
  - В корзине должна иметься кнопка для возврата к каталогу
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность постраничного вывода каталога товаров
  - В каталоге для каждого товара нужно выводить название, рейтинг, цену со скидкой и без нее, и больше ничего лишнего
  - В русскоязычной версии сайта все должно быть переведено на русский язык
  - Все элементы интерфейса должны быть корректно отрисованы
  - Пользователь должен иметь возможность сброса фильтра по категории
